"""Numerical motor of PAdicMIDI: Phase I (echo) + hierarchical p-adic tower."""

from padicmidi.core.config import (
    ALPHA,
    DEFAULT_BIN_BEATS,
    DEFAULT_BIN_SECONDS,
    DEFAULT_K,
    DEFAULT_KCHILD,
    DEFAULT_M,
    DEFAULT_SEED,
    DEFAULT_STEP,
    MAX_WINDOWS_PER_RESIDUE,
    SUPPORTED_PRIMES,
    default_nmax,
)
from padicmidi.core.echo import (
    parse_midi_notes_seconds,
    parse_midi_notes_beats,
    chroma_series_duration,
    chroma_series_duration_beats,
    onset_density_series,
    onset_density_series_beats,
    series_with_rhythm,
    spectral_flux_series,
    zscore_series,
)
from padicmidi.core.hierarchical import (
    build_X_seconds,
    build_X_beats,
    build_W_n,
    get_windows,
    aggregate_median,
    dist_matrix,
    kmeans_numpy,
    run_hierarchical,
)

__all__ = [
    "ALPHA",
    "DEFAULT_BIN_BEATS",
    "DEFAULT_BIN_SECONDS",
    "DEFAULT_K",
    "DEFAULT_KCHILD",
    "DEFAULT_M",
    "DEFAULT_SEED",
    "DEFAULT_STEP",
    "MAX_WINDOWS_PER_RESIDUE",
    "SUPPORTED_PRIMES",
    "default_nmax",
    "parse_midi_notes_seconds",
    "parse_midi_notes_beats",
    "chroma_series_duration",
    "chroma_series_duration_beats",
    "onset_density_series",
    "onset_density_series_beats",
    "series_with_rhythm",
    "spectral_flux_series",
    "zscore_series",
    "build_X_seconds",
    "build_X_beats",
    "build_W_n",
    "get_windows",
    "aggregate_median",
    "dist_matrix",
    "kmeans_numpy",
    "run_hierarchical",
]
